name: Scheduled Python Script APIMS

on:
  schedule:
    # Execute the task at 40 minutes past every hour.
    # This cron expression means:
    # 40: minute 40
    # *: every hour
    # *: every day of the month
    # *: every month
    # *: every day of the week
    - cron: '40 * * * *'
  workflow_dispatch: # Uncomment this line to allow manual triggers from the GitHub UI

permissions:
  contents: write  # This permission is crucial to allow the workflow to push changes to the repository

jobs:
  run-python-script:
    runs-on: ubuntu-latest # Specifies the operating system for the job
    name: Run Python Script # Name of the job

    steps:
    - name: Checkout code # Step to clone the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Needed for 'git pull --rebase' later, fetches all history

    - name: Set up Python # Step to set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.9 # Specify the Python version to use

    - name: Install dependencies # Step to install required Python packages
      run: |
        python -m pip install --upgrade pip # Upgrade pip to the latest version
        pip install pandas requests pytz urllib3 # Install necessary libraries

    - name: Run Python Script
      run: |
        python cron_apims.py
        cd data_apims
        git config --global user.email "booluckgmie@gmail.com"
        git config --global user.name "booluckgmie"
        git pull
        git add .
        git commit -m "Update data"
        git push --force  # Use the --force flag to forcefully push changes
