name: Scheduled Python Script APIMS

on:
  schedule:
    - cron: '40 * * * *' # Execute the task at 40 minutes past every hour.
  # workflow_dispatch: # Allow manual triggers

permissions:
  contents: write  # Allow pushing to repository

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    name: Run Python Script
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Needed for pushing changes

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests pytz urllib3

    - name: Run Python Script
      run: |
        set -e
        python cron_apims.py

    - name: Reset workspace to avoid unstaged changes
      run: |
        git reset --hard
        git clean -fd  # Remove untracked files to avoid conflicts

    - name: Commit and Push Data
      run: |
        cd data_apims
        git config --global user.email "booluckgmie@gmail.com"
        git config --global user.name "booluckgmie"
        git pull --rebase
        git add .
        git commit -m "Update data" || echo "No changes to commit"
        git push
