name: Schedule Sabah Jobs Scraper

on:
  # push:
  #  branches: [ master ] 
  schedule:
    # Run every Wednesday at 10:00 AM Malaysia Time (UTC+8)
    # The cron expression is in UTC. 10 AM MYT is 2 AM UTC.
    - cron: '0 2 * * 3'

permissions:
  contents: write  # Needed for committing and pushing changes

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    name: Run Python Script

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for pushing changes

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      # Remove Node.js if not required
      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests pytz urllib3 tqdm beautifulsoup4 openpyxl

      - name: Run Python Script and Commit Changes
        run: |
          set -e
          python jobSabah_auto.py
          cd data_jobsabah
          git config --global user.email "booluckgmie@gmail.com"
          git config --global user.name "booluckgmie"
          git pull --rebase origin master || echo "No remote changes to pull."
          git add .
          git commit -m "Update data" || echo "No changes to commit"
          git push
